apiVersion: v1
entries:
  karvdash:
  - apiVersion: v2
    created: "2021-03-23T11:18:20.107824221Z"
    description: Karvdash provides a complete software stack for performing data science
      on Kubernetes
    digest: 7af593b35b77b7f4ee7166712d351d61b07903dd91c867128e58ae7a359f3597
    kubeVersion: '>= 1.15.0'
    name: karvdash
    sources:
    - https://github.com/CARV-ICS-FORTH/karvdash
    type: application
    urls:
    - https://CARV-ICS-FORTH.github.io/karvdash/chart/karvdash-2.0.0.tgz
    version: 2.0.0
generated: "2021-03-23T11:18:20.105022721Z"
