apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-webhook
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  default.conf: |
    server {
        listen 443 ssl;
        server_name {{ .Release.Name }}.{{ .Release.Namespace }}.svc;

        ssl_certificate         /etc/ssl/keys/tls.crt;
        ssl_certificate_key     /etc/ssl/keys/tls.key;

        ssl_session_cache       builtin:1000 shared:SSL:10m;
        ssl_protocols           TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers             HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
        ssl_prefer_server_ciphers on;

        location / {
            proxy_set_header    Host $host;
            proxy_set_header    X-Real-IP $remote_addr;
            proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header    X-Forwarded-Proto $scheme;

            # Fix the “It appears that your reverse proxy set up is broken" error.
            proxy_pass          http://127.0.0.1:80;
            proxy_read_timeout  30;

            proxy_redirect      http://127.0.0.1:80 https://{{ .Release.Name }}.{{ .Release.Namespace }}.svc;
        }
    }
