{{- $filesURL := (required "You must set karvdash.filesURL to the base URL for the private and shared file domains" .Values.karvdash.filesURL) | urlParse }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - image: nginx:1.19.6-alpine
        name: proxy
        env:
        - name: NGINX_ENTRYPOINT_QUIET_LOGS
          value: "1"
        ports:
        - containerPort: 80
          name: https
        volumeMounts:
        - name: {{ .Release.Name }}-proxy-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        {{- if or .Values.karvdash.logsVolumeClaim .Values.karvdash.logsHostPath }}
        - name: {{ .Release.Name }}-logs-volume
          mountPath: /var/log/nginx
          subPath: proxy
        {{- end }}
      - image: nginx:1.19.6-alpine
        name: webhook
        env:
        - name: NGINX_ENTRYPOINT_QUIET_LOGS
          value: "1"
        ports:
        - containerPort: 443
          name: https
        volumeMounts:
        - name: {{ .Release.Name }}-webhook-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: {{ .Release.Name }}-webhook-secret
          mountPath: /etc/ssl/keys
          readOnly: true
        {{- if or .Values.karvdash.logsVolumeClaim .Values.karvdash.logsHostPath }}
        - name: {{ .Release.Name }}-logs-volume
          mountPath: /var/log/nginx
          subPath: webhook
        {{- end }}
      - image: {{- if .Values.image }} {{ .Values.image }} {{- else }} carvicsforth/karvdash:v{{ .Chart.Version }} {{- end }}
        name: karvdash
        env:
        - name: DJANGO_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: django-secret
        - name: DJANGO_DEBUG
          value: {{ .Values.karvdash.djangoDebug | quote }}
        - name: KARVDASH_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: admin-password
        - name: KARVDASH_DASHBOARD_TITLE
          value: {{ .Values.karvdash.dashboardTitle | quote}}
        - name: KARVDASH_DASHBOARD_THEME
          value: {{ .Values.karvdash.dashboardTheme | quote}}
        - name: KARVDASH_ISSUES_URL
          value: {{ .Values.karvdash.issuesURL | quote }}
        - name: KARVDASH_INGRESS_URL
          value: {{ required "You must set karvdash.ingressURL to the ingress URL used" .Values.karvdash.ingressURL | quote}}
        - name: KARVDASH_DOCKER_REGISTRY
          value: {{ .Values.karvdash.dockerRegistry | quote}}
        - name: KARVDASH_DOCKER_REGISTRY_NO_VERIFY
          value: {{ .Values.karvdash.dockerRegistryNoVerify | quote }}
        - name: KARVDASH_DATASETS_AVAILABLE
          value: {{ .Values.karvdash.datasetsAvailable | quote }}
        - name: KARVDASH_SERVICE_DOMAIN
          value: {{ printf "%s.%s.svc" .Release.Name .Release.Namespace | quote }}
        - name: KARVDASH_FILES_URL
          value: {{ .Values.karvdash.filesURL | quote }}
        - name: KARVDASH_ALLOWED_HOSTPATH_DIRS
          value: {{ .Values.karvdash.allowedHostPathDirs | quote }}
        ports:
        - containerPort: 8000
          name: http
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
        - name: {{ .Release.Name }}-state-volume
          mountPath: /db
        {{- if eq $filesURL.scheme "file" }}
        - name: {{ .Release.Name }}-private-volume
          mountPath: /private
        - name: {{ .Release.Name }}-shared-volume
          mountPath: /shared
        {{- end }}
      volumes:
      - name: {{ .Release.Name }}-proxy-config
        configMap:
          name: {{ .Release.Name }}-proxy
          defaultMode: 0644
      - name: {{ .Release.Name }}-webhook-secret
        secret:
          secretName: {{ .Release.Name }}-webhook
      - name: {{ .Release.Name }}-webhook-config
        configMap:
          name: {{ .Release.Name }}-webhook
          defaultMode: 0644
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
      {{- if .Values.karvdash.logsVolumeClaim }}
      - name: {{ .Release.Name }}-logs-volume
        persistentVolumeClaim:
          claimName: {{ .Values.karvdash.logsVolumeClaim }}
      {{- else if .Values.karvdash.logsHostPath }}
      - name: {{ .Release.Name }}-logs-volume
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-logs-pvc
      {{- end }}
      - name: {{ .Release.Name }}-state-volume
        persistentVolumeClaim:
          claimName: {{- if .Values.karvdash.stateVolumeClaim }} {{ .Values.karvdash.stateVolumeClaim }} {{- else }} {{ .Release.Name }}-state-pvc {{- end }}
      {{- if eq $filesURL.scheme "file" }}
      - name: {{ .Release.Name }}-private-volume
        hostPath:
          path: {{ printf "%s/private" $filesURL.path | clean | quote }}
      - name: {{ .Release.Name }}-shared-volume
        hostPath:
          path: {{ printf "%s/shared" $filesURL.path | clean | quote }}
      {{- end }}
