apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: genome-pvc
  labels:
    app: genome
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
