apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: karvdash-pvc
  labels:
    app: karvdash
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
