apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: templates.karvdash.carv.ics.forth.gr
spec:
  group: karvdash.carv.ics.forth.gr
  scope: Namespaced
  names:
    kind: Template
    listKind: TemplateList
    plural: templates
    singular: template
  versions:
    - name: v1
      served: true
      storage: true
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            path:
              type: "string"
