# zeppelin.gene.yaml

apiVersion: v1
kind: Service
metadata:
  name: $NAME
spec:
  type: LoadBalancer
  ports:
  - port: $PORT
    targetPort: 8080
  selector:
    app: $NAME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $NAME
  template:
    metadata:
      labels:
        app: $NAME
    spec:
      containers:
      - name: $NAME
        image: apache/zeppelin:0.8.2
        ports:
        - containerPort: 8080
        env:
        - name: ZEPPELIN_ADDR
          value: 0.0.0.0
        - name: ZEPPELIN_PORT
          value: "8080"
        - name: ZEPPELIN_NOTEBOOK_DIR
          value: ${REMOTE}/zeppelin/notebook
        - name: ZEPPELIN_LOG_DIR
          value: ${REMOTE}/zeppelin/logs
---
kind: Gene
name: Zeppelin
description: Notebook server
variables:
- name: NAME
  default: zeppelin
- name: PORT
  default: 8080
- name: REMOTE
  default: /remote
