# kafka.template.yaml

apiVersion: v1
kind: Service
metadata:
  name: $NAME
spec:
  type: ClusterIP
  ports:
  - port: 9092
    name: kafka
  - port: 2181
    name: zeppelin
  selector:
    app: $NAME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $NAME
  template:
    metadata:
      labels:
        app: $NAME
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:2.5.0
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: localhost:2181
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: PLAINTEXT://localhost:9092
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
      - name: zookeeper
        image: bitnami/zookeeper:3.6.1
        ports:
        - containerPort: 2181
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
---
kind: Template
name: Kafka
description: Streaming platform
singleton: yes
variables:
- name: NAME
  default: kafka
- name: HOSTNAME
  default: kafka.example.com
- name: REMOTE
  default: /remote
