# kafka.template.yaml

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: $NAME
spec:
  rules:
  - host: $HOSTNAME
    http:
      paths:
      - backend:
          serviceName: $NAME
          servicePort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: $NAME
spec:
  type: ClusterIP
  ports:
  - port: 9000
  selector:
    app: $NAME
  publishNotReadyAddresses: true
---
apiVersion: v1
kind: Pod
metadata:
  name: kafdrop
  labels:
    app: $NAME
spec:
  hostname: kafdrop
  subdomain: $NAME
  containers:
  - name: kafdrop
    image: obsidiandynamics/kafdrop
    ports:
    - containerPort: 9000
    env:
    - name: KAFKA_BROKERCONNECT
      value: kafka.${NAME}:9092
---
apiVersion: v1
kind: Pod
metadata:
  name: kafka
  labels:
    app: $NAME
spec:
  hostname: kafka
  subdomain: $NAME
  containers:
  - name: kafka
    image: bitnami/kafka:latest
    ports:
    - containerPort: 9092
    env:
    - name: KAFKA_CFG_ZOOKEEPER_CONNECT
      value: zookeeper.${NAME}:2181
    - name: KAFKA_CFG_ADVERTISED_LISTENERS
      value: PLAINTEXT://localhost:9092
    - name: ALLOW_PLAINTEXT_LISTENER
      value: "yes"
---
apiVersion: v1
kind: Pod
metadata:
  name: zookeeper
  labels:
    app: $NAME
spec:
  hostname: zookeeper
  subdomain: $NAME
  containers:
  - name: zookeeper
    image: bitnami/zookeeper:latest
    ports:
    - containerPort: 2181
    env:
    - name: ALLOW_ANONYMOUS_LOGIN
      value: "yes"
---
kind: Template
name: Kafka
description: Streaming platform
singleton: yes
variables:
- name: NAME
  default: kafka
- name: HOSTNAME
  default: kafka.example.com
- name: REMOTE
  default: /remote
