# redis.template.yaml

apiVersion: v1
kind: Service
metadata:
  name: $NAME
spec:
  type: ClusterIP
  ports:
  - port: 6379
    name: redis
  selector:
    app: $NAME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $NAME
  template:
    metadata:
      labels:
        app: $NAME
    spec:
      containers:
      - name: $NAME
        image: redis:6.0.8
        ports:
        - containerPort: 6379
---
kind: Template
name: Redis
description: In-memory key-value store
variables:
- name: NAME
  default: redis
- name: HOSTNAME
  default: redis.example.com
