name: Publish docs and chart
on:
  push:
    tags:
      - 'v*'
jobs:
  docs:
    name: Publish docs
    runs-on: ubuntu-latest
    container: python:3.7.9-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y make git
      - name: Build and install client
        run: |
          (cd client && python setup.py install)
      - name: Build docs
        run: |
          pip install -r docs/requirements.txt
          (cd docs && make html)
      - name: Push docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          destination_dir: docs
          exclude_assets: '.github,.buildinfo'
  chart:
    name: Publish chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set version
        run: |
          VERSION=$(cat ./VERSION)
          echo "VERSION=${VERSION##*v}" >> $GITHUB_ENV
      - name: Publish chart to GitHub Pages
        if: ${{ !contains(env.VERSION, 'b') }}
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: chart
          target_dir: chart
          chart_version: ${{ env.VERSION }}
